# site settings
title: Le-Cong
subtitle: Thanh
email: congthanh.le@student.unimelb.edu.au
description: Ph.D. Student in Software Engineering <br /> at <a href='https://www.unimelb.edu.au/'>The University of Melbourne</a>
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://thanhlecongg.github.io" # the base hostname & protocol for your site
author:
street_address: Melbourne Connect, 700 Swanston Street
city: Melbourne
state: VIC
zip_code: 3053
country: Australia
phone: (84) 939251998

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/thanhlecongg
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/thanhlecong/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/ThanhLeCong2705

# build settings
markdown: kramdown

sass:
  style: compressed
